server:
  port: 8084
  servlet:
    context-path: /webchat

### THYMELEAF (THYMELEAF AutoConfiguration)
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  # 使用指定的配置文件
  profiles:
    active: dev
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  type-aliases-package: com.xcl.webchat.apply.**.entity
  mapper-locations: mapper/**/*.xml
  config-location: config/sqlMapConfig.xml